export enum IssueStatus {
  INDEFINIDA = "-",
  A_FAZER = "A FAZER",
  EM_REFINAMENTO = "EM REFINAMENTO",
  EM_EXECUCAO = "EM EXECUÇÃO",
  EM_TESTES = "EM TESTES",
  ENCERRADO = "ENCERRADO",
  ATIVADO = "ATIVADO",
  ENCERRADO_ATIVADO = "ENCERRADO/ATIVADO",
  CANCELADO = "CANCELADO",
}
